title: ERT - Visualization tool

pages:

 - title: Front page
   content:
    - EnsembleOverview:

 - title: Plot Viewer
   content:
    - ResponseComparison:

 - title: Observation Analyzer
   content:
    - ObservationAnalyzer:

 - title: Parameter Comparison Viewer
   content:
    - ParameterComparison:

 - title: Response Correlation Viewer
   content:
    - ResponseCorrelation:
