title: ERT - Visualization tool

pages:

 - title: Front page
   content:
    - EnsembleOverview:

 - title: Plot Viewer
   content:
    - ResponseComparison:

 - title: Observation Analyzer
   content:
    - ObservationAnalyzer:
