title: ERT - Visualization tool

pages:

 - title: Front page
   content:
    - Welcome to Webviz-ERT
    - EnsembleOverview:

 - title: Comparison Viewer
   content:
    - EnsembleComparison
    - EnsembleComparison:
