title: ERT - Visualization tool

pages:

 - title: Front page
   content:
    - EnsembleOverview:

 - title: Comparison Viewer
   content:
    - EnsembleComparison:

 - title: Response Comparison Viewer
   content:
    - ResponseComparison:
