title: Test of ERTViz plugins

pages:

 - title: Front page
   content:
    - Ensemble Oveview
    - EnsembleOverview:

 - title: Ensemble Viewer
   content:
    - Ensemble
    - Ensemble:

 - title: Comparison Viewer
   content:
    - EnsembleComparison
    - EnsembleComparison:

#  - title: Simulation time series
#    content:
#     - ERTTimeSeries:

#  - title: Parameter distribution
#    content:
#     - ERTParameterDistribution:
